name: Build


on:
  push:
    branches:
      - goupilhallayl

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.7]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies & build
        run: |
          npm ci
          npm run node-modules-front
          npm run build-github

      - name: tmp debug
        run: |
          du -h ./dist
          ls -la ./dist
